### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Bejta** [js223kz/1DV450_BIRDSPOTTER_CLIENT#25]
När man delar sin position det funkade bara i Firefox, men inte i Chrome.
Du har skrivit att applikation är anpassad för Firefox och det är extra funktionalitet som du har implementerad så jag bara nämner det.
Du kan se i bilden, och jag sitter i Malmö (och har tryckt allow position).
<img width="786" alt="screen shot 2016-08-24 at 16 10 11" src="https://cloud.githubusercontent.com/assets/8629282/17933702/5e0cde2c-6a15-11e6-9329-b0a1e15a65d9.png">

I start controller du har dependency MarkerService, men använder aldrig den vidare i koden.

```
StartController.$inject = ['ApiService', 'Constants', 'LayerService', 'LoginService', 'PositionService', 'MarkerService', '$scope', '$q']

    function StartController(ApiService, Constants, LayerService, LoginService, PositionService, MarkerService, $scope, $q)
```

När jag försökte spara en fågel, allt funkade bra (namnet "test"), men när jag försökte lägga en till birdspott och försöka spara, jag får följande:

<img width="816" alt="screen shot 2016-08-24 at 16 21 21" src="https://cloud.githubusercontent.com/assets/8629282/17934245/789108d4-6a17-11e6-8afc-0b4828ba4a39.png">

Sökfunktion funkar utmärkt.
Jag har inte hittat sätt se över en lista, och radera en birdspott eller en fågel. Det händer inget om man går till sin konto: /#/account route.
Så när det gäller routes, jag tror att följande kod:

<img width="760" alt="screen shot 2016-08-24 at 16 17 23" src="https://cloud.githubusercontent.com/assets/8629282/17934443/434e8fd8-6a18-11e6-88dc-f1ab1cbc312e.png">
kan utvecklas och att du behöver inte bygga URL som du gör med hjälp av konstanter i constantService:

```
 //Api-urls
            SPOTS_URL: '/spots',
            BIRDS_URL: '/birds',
            LOGIN_URL: '/login/',
            POSITION_URL: 'spots/position',
```

För övrigt, inloggning och sökfunktion fungerar perfekt, CRUD fungerar i stora delar (kanske jag missade Delete för att Account view öppnas inte), design är genomarbetat och väldigt bra (responsivt 👍 och snygg), finns directives och applikation uppfyller alla krav.

**Comment by js223kz** [comment]
Hej Jasmin,

tack för din feedback. Jag hade gjort ett tokigt tillägg i min kod precis innan jag publicerade applikationen som gjorde att det inte fungerade att radera, ändra eller lägga till en spot. Beklagar detta. Vill du testa igen så fungerar det nu :) Vet inte om det är i chrome du testar i, men accountview öppnas i Firefox och det är som du säger där man kan ändra och radera en spot. Jag använder en del ES6 syntax och vad jag förstår hade jag behövt lägga till Traceur eller Babel för att få det att fungera felfritt i Chrome därför valde jag att bara satsa på Firefox inför redovisningen.
Tack än en gång för din peer review. Ha de gott/ Johanna
